### ISSUE TITLE
It need to help to update to the last pymunk!

### ISSUE THREAD

**Issue by estevaofon** [estevaofon/angry-birds-python#10]
It would be great to be helped in this issue!

**Comment by robmcmullen** [comment]
I submitted a pull request with some fixes to get it to work on pymunk 6. I'm not sure if there are other things that need fixing, I'm just starting to look at your program. I found it because my kids wanted to create their own angry birds and this is a great place to start! Thanks for writing this and making it open source.

**Comment by estevaofon** [comment]
Hey Rob McMullen!
I'm very grateful already! I did not expect this issue to be seen so soon. I'm pleased to know that this game is going to be useful to your kids! I will have a look in your fixes, thanks again!

**Comment by robmcmullen** [comment]
You're welcome, thanks again for writing this. My kids were impressed and enjoyed playing with it. They're already talking about what kinds of levels they want to add.

**Comment by estevaofon** [comment]
You are welcome! I'm so glad your kids are having fun, you are an awesome dad. So nice they will create new levels, be welcome to submit those levels!
